fix: add contact links in the configuration template
LearnWithCommunity/support pull request #21
Opened 2021-12-05 18:59 UTC by Panquesito7

#### What does this PR do?

- Add contact links in the configuration template.

#### How can this be manually tested?

I don't think this applies here.

#### Any background context you want to provide?

Nope.

#### Is there any relevant issue to this PR?

Nope.

#### Questions

None.

2021-12-06 13:01 UTC, krishguptadev requested changes
- I've not seen this added [anywhere](https://github.com/nhcommunity/community/blob/main/.github/ISSUE_TEMPLATE/config.yml) [else](https://github.com/EddieHubCommunity/support/blob/main/.github/ISSUE_TEMPLATE/config.yml).
- Even if we want to add it, I would like the `dsc.gg` link and a better description

2021-12-06 13:02 UTC, krishguptadev commented
Marked as a draft PR, if you wanna bring any other thoughts. You can close if you think that we do not need these changes.

2021-12-06 20:32 UTC, Panquesito7 commented
> * I've not seen this added [anywhere](https://github.com/nhcommunity/community/blob/main/.github/ISSUE_TEMPLATE/config.yml) [else](https://github.com/EddieHubCommunity/support/blob/main/.github/ISSUE_TEMPLATE/config.yml).

https://github.com/web3community/.github/blob/main/.github/ISSUE_TEMPLATE/config.yml


> * Even if we want to add it, I would like the `dsc.gg` link and a better description

👍

2021-12-07 03:05 UTC, krishguptadev approved these changes

2021-12-07 03:05 UTC, merged